### ISSUE TITLE
Decrease log level ERROR -> WARN when messaging "Error in sending request"

### ISSUE THREAD

**Issue by deniaa** [vostok/clusterclient.core#7]
When error occured in sending request to one replica, but according to strategy we have another one attempt and this second attempt was successful, ERROR in message from first attempt looks embarassing.

Below is an example:
```
2020-01-13 11:30:39,142 INFO  [T-915c1ddf] Sending request 'GET datacore/api/'. Timeout = 30 seconds. Strategy = 'Sequential(equal-1)'.
2020-01-13 11:30:39,142 INFO  [T-915c1ddf] Sending request to replica 'http://replica9/' with timeout 30 seconds.
2020-01-13 11:30:40,168 ERROR [T-915c1ddf] Error in sending request. Status = UnknownError.
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
2020-01-13 11:30:40,174 INFO  [T-915c1ddf] Result: replica = 'http://replica9/'; code = 453 ('UnknownFailure'); verdict = Reject; time = 1.032 seconds.
2020-01-13 11:30:40,174 DEBUG [T-915c1ddf] Local base health for replica 'http://replica9/' has changed from 1.0000 to 0.5000.
2020-01-13 11:30:40,174 INFO  [T-915c1ddf] Sending request to replica 'http://replica8/' with timeout 28.967 seconds.
2020-01-13 11:30:40,220 INFO  [T-915c1ddf] Result: replica = 'http://replica8/'; code = 200 ('Ok'); verdict = Accept; time = 45.923 milliseconds.
2020-01-13 11:30:40,220 INFO  [T-915c1ddf] Success. Response code = 200 ('Ok'). Time = 1.079 seconds.
```

May be all failed attempts to send request to one replica should not be logged with ERROR level, but if the global result was not "Success", this is should be noticed in additional message?

**Comment by asvyazin** [comment]
More context:


This error is actually logged in clusterclient.transport.webrequest in method `WebRequestTransport.HandleWebException`. This method tries to analyze property `WebException.Status` and in some cases it logs warning (`WebExceptionStatus.ConnectFailure` and some others), in some cases it doesn't log anything but in the case of unknown error status it logs error (which makes some sense, I think).


But! It looks to me that in .net core only 2 `WebExceptionStatus`-es are actually used: `UnknownError` and `NameResolutionFailure` (why??): https://github.com/dotnet/runtime/blob/e0f6402817f2c9f4c4375670268779b3dfc6dad8/src/libraries/System.Net.Requests/src/System/Net/WebException.cs#L110. So now in .net core any `WebException` on each request attempt is logged as error. And I'm not entirely sure which way to fix it is the best: log all exceptions as warnings on the transport level and only log errors on some higher level (if all attempts were failed)?

**Comment by iloktionov** [comment]
The exception described in this issue only happens when using `WebRequestTransport` under .NET Core, which should be avoided at all costs as `HttpWebRequest` is seriously broken in Core runtimes. Client libraries are expected to use universal (https://github.com/vostok/clusterclient.transport) or socket (https://github.com/vostok/clusterclient.transport.sockets) transport implementations when targeting Core.

However, I have also decided to convert almost all of the transport-level error logging to warnings: https://github.com/vostok/clusterclient.transport.webrequest/commit/a849ad874f90f9c52a274d9235056834bae6dc0b.

An error will be logged by `ClusterClient` itself if all replicas happen to fail.
